-------------------------------------------SEQUENCES---------------------------------------------
CREATE SEQUENCE EVENT.SQ_EVENTS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE EVENT.SQ_USERS INCREMENT BY 1 START WITH 1; 
CREATE SEQUENCE EVENT.SQ_ADDRESS INCREMENT BY 1 START WITH 1;
